In [1]:
import numpy as np
import os
import glob
from _CONSTANTS.config import Config
import  behavior.cristian_behavior_analysis as analysis
import filter
import reduce
import plot
import matplotlib.pyplot as plt
import matplotlib as mpl
from psth.format import *
from collections import defaultdict

mpl.rcParams['pdf.fonttype'] = 42
mpl.rcParams['ps.fonttype'] = 42
mpl.rcParams['font.family'] = 'arial'
ax_args_copy = ax_args.copy()
ax_args_copy.update({'ylim':[-5, 85], 'yticks':[0, 40, 80]})
bool_ax_args_copy = ax_args.copy()
bool_ax_args_copy.update({'ylim':[-0.05, 1.05], 'yticks':[0, .5, 1]})

class OFC_PT_Config():
    path = r'C:\Users\P\Desktop\MANUSCRIPT_DATA\Nikki Data\OFC Pretraining'
    # phase = 'PT'
    name = 'OFC_PT'

class OFC_PT_RELEASED_Config():
    path = r'C:\Users\P\Desktop\MANUSCRIPT_DATA\Nikki Data\OFC Pretraining\Pretraining, Laser OFF'
    phase = 'PT'
    name = 'OFC_PT_RELEASED'

class OFC_DT_HALO_PT_Config():
    path = r'C:\Users\P\Desktop\MANUSCRIPT_DATA\Nikki Data\OFC Discrim\PT'
    phase = 'DT'
    name = 'OFC_DT_HALO_PT'

class OFC_DT_HALO_DT_Config():
    path = r'C:\Users\P\Desktop\MANUSCRIPT_DATA\Nikki Data\OFC Discrim\PT'
    phase = 'DT'
    name = 'OFC_DT_HALO_DT'

class MPFC_PT_Config():
    path = r'C:\Users\P\Desktop\MANUSCRIPT_DATA\Nikki Data\OFC Discrim\Discrimination'
    phase = 'PT'
    name = 'MPFC_PT'

indices = analysis.Indices()
constants = analysis.Constants()
config = Config()

experiment = OFC_PT_Config
save_path = os.path.join(Config.LOCAL_FIGURE_PATH, 'BEHAVIOR_CRISTIAN', experiment.name)
directories = [constants.pretraining_directory, constants.discrimination_directory]
res = defaultdict(list)
for directory in directories:
    halo_files = sorted(glob.glob(os.path.join(experiment.path, directory, constants.halo + '*')))
    yfp_files = sorted(glob.glob(os.path.join(experiment.path, directory, constants.yfp + '*')))
    res1 = analysis.parse(halo_files, experiment=experiment, condition=constants.halo, phase = directory)
    res2 = analysis.parse(yfp_files, experiment=experiment, condition=constants.yfp, phase = directory)
    reduce.chain_defaultdicts(res, res1)
    reduce.chain_defaultdicts(res, res2)
analysis.analyze(res)

ModuleNotFoundError: No module named 'psth.format'

In [3]:
combs, ixs = filter.retrieve_unique_entries(res, ['mouse'])

In [4]:
combs

[('H01',),
 ('H02',),
 ('H03',),
 ('H04',),
 ('H05',),
 ('Y01',),
 ('Y02',),
 ('Y03',),
 ('Y04',),
 ('Y05',),
 ('Y06',)]

In [5]:
ixs

[array([0, 1], dtype=int64),
 array([2, 3], dtype=int64),
 array([ 4,  5, 22, 23], dtype=int64),
 array([6, 7], dtype=int64),
 array([ 8,  9, 24, 25], dtype=int64),
 array([10, 11, 26, 27], dtype=int64),
 array([12, 13, 28, 29], dtype=int64),
 array([14, 15, 30, 31], dtype=int64),
 array([16, 17, 32, 33], dtype=int64),
 array([18, 19, 34, 35], dtype=int64),
 array([20, 21, 36, 37], dtype=int64)]

In [22]:
ix = ixs[2]
comb = combs[2]

In [23]:
        phases = res['phase'][ix]
        pt_mask = ix[phases == 'Pretraining']
        dt_mask = ix[phases == 'Discrimination']

        pt_trials = res['trials'][pt_mask]
        total_pt_trials = np.sum([len(x) for x in pt_trials])
        dt_trials = res['trials'][dt_mask]
        modified_dt_trials = [x + total_pt_trials for x in dt_trials]
        res['trials'][dt_mask] = modified_dt_trials

array([22, 23], dtype=int64)